baseURL = "https://nara-wu-slc.jp/"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false
enableGitInfo = true

[module]
proxy = "direct"

[module.hugoVersion]
extended = true
min = "0.160.1"

[[module.imports]]
path = "github.com/google/docsy/theme"
disable = false

[caches]
[caches.images]
dir = ":cacheDir/images"

[params]
content_max_width = "50vw"
toc_root = false

[params.copyright]
authors = "Lab4SLC, Nara Women's University"
from_year = 2024

[params.docs]
toc_level = 1
toc_in_sidebar = true

[params.ui]
sidebar_menu_compact = false
sidebar_menu_foldable = true
breadcrumb_disable = true
ul_show = 1

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[languages]
[languages.ja]
label = "日本語"
contentDir = "content/ja"
title = "音声・言語・コミュニケーション研究室 (Lab4SLC)"
weight = 1

[languages.ja.params]
description = "奈良女子大学 生活情報通信科学コース 音声・言語・コミュニケーション研究室の公式Webページ"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"

[languages.en]
label = "English"
contentDir = "content/en"
title = "Laboratory for Speech, Language, and Communication (Lab4SLC)"
weight = 2

[languages.en.params]
description = "Official Webpage of Laboratory for Speech, Language, and Communication (Lab4SLC), Nara Women's University"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"
